name: BDS Java CI

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Only do this when tagged
      run: echo "Hello tag ${{ github.ref }}"
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.5
    - name: Download dependeices with Maven
      run: mvn dependency:resolve dependency:copy-dependencies
    - name: Build with Ant
      run: ant
    - name: Build GO
      env:
        GOPATH: /home/runner/work/bds/bds/go/bds
        GOROOT: /opt/hostedtoolcache/go/1.16.5/x64
        GO111MODULE: auto
      run: |
        echo "$HOME/go/bin" >> $GITHUB_PATH
        mkdir -p /home/runner/go
        cd "go/bds/"
        go get -v github.com/aws/aws-sdk-go/aws
        go get -v github.com/aws/aws-sdk-go/aws/session
        go get -v github.com/aws/aws-sdk-go/service/ec2
        go get -v github.com/aws/aws-sdk-go/service/s3
        go get -v github.com/aws/aws-sdk-go/service/sqs
        go env
        go build
        go fmt
    - name: Build final Binary GO + JAR
      run: |
        pwd
        cat go/bds/bds build/bds.jar > bds_linux
        chmod +x bds_linux
        ./bds_linux --help
    - name: Upload linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary-linux
        path: |
          bds_linux

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Only do this when tagged
      run: echo "Hello tag ${{ github.ref }}"
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.5
    - name: Download dependeices with Maven
      run: mvn dependency:resolve dependency:copy-dependencies
    - name: Build with Ant
      run: ant
    - name: Build GO
      env:
        GOPATH: /Users/runner/work/bds/bds/go/bds
        GO111MODULE: auto
      run: |
        go env
        echo "$HOME/go/bin" >> $GITHUB_PATH
        mkdir -p /Users/runner/go
        cd "go/bds/"
        go get -v github.com/aws/aws-sdk-go/aws
        go get -v github.com/aws/aws-sdk-go/aws/session
        go get -v github.com/aws/aws-sdk-go/service/ec2
        go get -v github.com/aws/aws-sdk-go/service/s3
        go get -v github.com/aws/aws-sdk-go/service/sqs
        go env
        go build
        go fmt
    - name: Build final Binary GO + JAR
      run: |
        pwd
        cat go/bds/bds build/bds.jar > bds_macos
        chmod +x bds_macos
        ./bds_macos --help
    - name: Upload macos artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary-macos
        path: |
          bds_macos
         


  release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//} 
      - uses: actions/download-artifact@v2
        with:
          name: binary-linux
          path: bds_linux
      - uses: actions/download-artifact@v2
        with:
          name: binary-macos
          path: bds_macos
      - run: |
          mkdir release-linux
          mkdir release-macos
          mv bds_linux release-linux/bds
          mv bds_macos release-macos/bds
          echo ${{ github.sha }} > release.txt
          tar -C release-linux -czf bds-linux.tar.gz ./
          tar -C release-macos -czf bds-macos.tar.gz ./
      - name: List Files
        run: |
          ls -laht
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
             release.txt
             bds-linux.tar.gz
             bds-macos.tar.gz
